### ISSUE TITLE
Project list in navigation bar is not populated when viewing build details

### ISSUE THREAD

**Issue by BradyBonnette** [codeship/documentation#255]
Not entirely sure if this is intended behavior, but I noticed that the project list in the navigation bar at the top is not populated with projects when viewing the test output details of a particular build.

Steps to recreate:
1.) Log into CodeShip with an account that belongs to an organization that has at least one project with at least one build / test run (regardless if it was successful or not).
2.) Select the organization from the organization selection menu in the navigation bar
3.) Select the project from the "Select Project..." dropdown menu in the navigation bar
4.) Click on Success or Failed button for any of the builds / test runs for that particular project
5.) You should now be viewing the test output page with all the command and their respective outputs.
6.) Click the "Select Project..." dropdown menu in the navigation bar

Expected:
7.)  The Select Project menu appears with all the projects for the organization

Actual:
7.) The Select Project menu appears, but it is empty and contains the text "No projects yet"

Again, I am not sure if this is a bug.

**Comment by mlocher** [comment]
Hey @BradyBonnette, sorry we never responded to this ticket. I followed the steps outlined above and the bug is fixed now.

For future bug reports, please send us an email via support@codeship.com or create a new topic on our community forum at https://community.codeship.com.

As per our [Contributing Guidelines](https://github.com/codeship/documentation/blob/master/CONTRIBUTING.md#when-not-to-submit-an-issue) this repository is only used for bugs specific to our Documentation.
