### ISSUE TITLE
incomplete IAM perms

### ISSUE THREAD

**Issue by mdespriee** [codeship/documentation#258]
in https://codeship.com/documentation/continuous-deployment/deployment-to-elastic-beanstalk/

the following iam authorization are missing : 
* cloudformation:DescribeStackResources (both cloudformation:DescribeStackResource and cloudformation:DescribeStackResources exist in AWS)
* cloudformation:DescribeStacks
* cloudformation:DescribeStackEvents

All these requirements come from error messages I got during my tests on AWS

**Comment by mlocher** [comment]
Ahoy, 

the permissions listed on the documentation article only list the bare minimum if your application doesn't require any other AWS services. As soon as you require additional services for your application, you need to extend the IAM policies, which is the case with your project.

**Comment by mdespriee** [comment]
Well, no, I just tried to setup a simple deploy to beanstalk, nothing more.
I followed the procedure in this doc, and had several errors, AWS
complaining about these missing, specific, permissions.

You know, I just want to help and share my own experience in following this
doc...

Mathieu

**Comment by mlocher** [comment]
I'll take a look at the sample application, maybe Amazon pushed some changes, which require an updated IAM policy.

Thanks for letting us know, this is really appreciated!

**Comment by wes-r** [comment]
Just ran into this on a new beanstalk and new codeship deploy setup.

@mlocher Looks like you added `cloudformation:DescribeStackResource` but not `cloudformation:DescribeStackResources` to the doc. Note the extra "s"! Both are required.

It'd also be nice if yall just used a single code snippet with the full json policy. Instead of the user having to copy and paste things around (ran into lacking "Version" when I took the biggest json on the page).

**Comment by mlocher** [comment]
@wes-r Thanks for spotting this, I created a new PR with the missing actions. 

As for a single policy, this is complicated as it depends on the AWS services your application uses. So we can come up with a basic template, but for most applications you need to adapt it to your specific needs in any case.
