### ISSUE TITLE
Should mention creation of the `Gemfile`

### ISSUE THREAD

**Issue by earnold** [codeship/documentation#489]
Location: https://github.com/codeship/documentation/blob/master/_posts/docker/guide/2015-06-10-getting-started.md

In this tutorial, you describe every step except for creating the Gemfile and running bundler locally (to create the Gemfile.lock)

It was easy to figure out what was wrong, but I think tweaking this would be a nice improvement. 

A fix would be to say something like: 

Create a `Gemfile` and add to it the following: 

```
source 'https://rubygems.org'

ruby '2.2.1'

gem 'redis'
gem 'pg'
```

**Comment by mlocher** [comment]
Hey @earnold, 

the sample repository at https://github.com/codeship/ci-guide/tree/master/part1 already has the `Gemfile.lock` included in the repository, so we don't mention the steps for how to create it in the guide.

If you don't have the `Gemfile.lock` available yet, I'd recommend running the `bundle install` command to create it inside a Docker container as well. Otherwise you'd need to install the required version of Ruby and Bundler outside of the container, partly defeating the purpose.

To do this, you'd need to modify the `Dockerfile` to not copy the `Gemfile.lock` during the build process and then use `docker run` to run a Bundler. 

With a `Dockerfile` like the following

```Dockerfile
# base on latest ruby base image
FROM ruby:2.2.1
MAINTAINER marko@codeship.com

ENV DEBIAN_FRONTEND=noninteractive 

# update and install dependencies
RUN \
  apt-get update -qq && \
  apt-get install -y \
    apt-utils \
    build-essential\
    libpq-dev \
    nodejs

# setup app folders
RUN mkdir /app
WORKDIR /app

# copy over Gemfile
COPY Gemfile ./
```

you'd then run the following commands

```
docker build --tag app .
docker run -it -v $(pwd):/app app bundle install
```

That will run `bundle install` in the container, but as the current directory (`$(pwd)`) is mounted  as a volume to `/app` inside the container, any changes made by Bundler will be reflected in the current directory as well.

Once the `Gemfile.lock` is available you could then switch to the complete `Dockerfile` and continue building your application.
